unmanned_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from unmanned import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('login/', views.login),
    path('register/', views.register),
    path('profile/', views.get_profile),
    path('profile/record/', views.get_record),
    path('logout/', views.logout),
    path('captcha', include('captcha.urls')),
    path('confirm/', views.user_confirm),
    path('profile/take_pic/', views.take_pic),
    path('upload_image', views.upload_image, name='upload_image'),
    path('test/', views.test_page),
    path('admin_page/', views.admin_report, name='admin_report'),
    path('sales/', views.sales, name='sales'),
    path('admin_page/stock/', views.stock, name='stock'),
    path('admin_page/member_information/', views.member_information, name='member_information'),
    path('admin_page/member_analysis/', views.member_analysis, name='member_analysis'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unmanned/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Category(models.Model):
    category_no = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'category'

    def __str__(self):
        return self.category_name


class ConfirmString(models.Model):
    c_id = models.AutoField(primary_key=True)
    c_user = models.OneToOneField('Member', models.DO_NOTHING, db_column='c_user', blank=True, null=True)
    code = models.CharField(blank=True, null=True, max_length=256)
    c_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = True
        db_table = 'confirmString'
        ordering = ["-c_time"]
        verbose_name = "確認碼"
        verbose_name_plural = "確認碼"

    def __str__(self):
        return self.c_user.member_name + ":   " + self.code


class InOrOut(models.Model):
    come_time = models.DateTimeField(primary_key=True)
    left_time = models.DateTimeField(blank=True, null=True)
    phone_number = models.ForeignKey('Member', models.DO_NOTHING, db_column='phone_number', blank=True, null=True)
    satisfaction = models.IntegerField(null=True, blank=True)
    inorout = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'inorout'

    def __str__(self):
        return str(self.come_time) + "： " + self.phone_number.member_name


class Member(models.Model):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    phone_number = models.CharField(primary_key=True, max_length=10)
    member_name = models.CharField(max_length=128)
    line_account = models.CharField(unique=True, max_length=255, blank=True, null=True)
    birthdate = models.DateTimeField(blank=True, null=True)
    e_mail = models.CharField(unique=True, max_length=255, blank=True, null=True)
    credit_card = models.CharField(max_length=50, blank=True, null=True)
    photo = models.ImageField(upload_to='profile_image', blank=True)
    member_password = models.CharField(max_length=255, blank=True, null=True)
    has_confirmed = models.BooleanField(default=False)
    c_time = models.DateTimeField(auto_now_add=True)
    has_photo = models.BooleanField(default=False)
    gender = models.CharField(max_length=32, choices=gender, default="男")

    class Meta:
        managed = True
        db_table = 'member'

    def __str__(self):
        return self.member_name


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=50, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    category_no = models.ForeignKey(Category, models.DO_NOTHING, db_column='category_no', blank=True, null=True)
    stock = models.IntegerField(blank=True, null=True)
    product_url = models.CharField(max_length=255, blank=True, null=True)
    picture_url = models.CharField(max_length=255, blank=True, null=True)
    re_product_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'product'

    def __str__(self):
        return self.product_name


class Purchase(models.Model):
    purchase_no = models.AutoField(primary_key=True)
    come_time = models.ForeignKey(InOrOut, models.DO_NOTHING, db_column='come_time', blank=True, null=True)
    product = models.ForeignKey(Product, models.DO_NOTHING, blank=True, null=True)
    quantity = models.IntegerField(blank=True, null=True)
    satisfaction = models.IntegerField(blank=True, null=True)
    neededcall = models.IntegerField(blank=True, default=0)

    class Meta:
        managed = True
        db_table = 'purchase'

    def __str__(self):
        return str(self.purchase_no) + ": " + str(self.come_time)

unmanned/forms.py
from django import forms
from captcha.fields import CaptchaField


class UserForm(forms.Form):
    user_email = forms.CharField(label="帳號", max_length=255, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                        'placeholder': '請輸入信箱'}))
    password = forms.CharField(label="密碼", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='驗證碼', error_messages={"invalid": "驗證碼錯誤"})


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    email = forms.EmailField(label="信箱", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label="用戶名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密碼", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="確認密碼", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    image = forms.ImageField(label="上傳照片")
    phone_number = forms.CharField(label="電話", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    birthday = forms.DateField(label='生日', widget=forms.SelectDateWidget(years=range(2022, 1930, -1)))
    sex = forms.ChoiceField(label='性別', choices=gender)
    captcha = CaptchaField(label='驗證碼', error_messages={"invalid": "驗證碼錯誤"})

unmanned/views.py
from django.shortcuts import render, HttpResponse
from django.shortcuts import redirect
from . import models, forms
import hashlib
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json
import re
import base64
import os
import datetime
from django.db.models import Sum
from django.views.decorators.cache import cache_page


# Create your views here.


def index(request):
    if request.session.get('is_login', None):
        hot_product = models.Purchase.objects.values('product__product_url', 'product__picture_url').\
            annotate(sum_quantity=Sum('quantity')).order_by('-sum_quantity')[:3]
    else:
        pass
    return render(request, 'client/index.html', locals())


def login(request):
    if request.session.get('is_login', None):
        return redirect("/index/")
    if request.method == "POST":
        login_form = forms.UserForm(request.POST)
        message = "請檢查填寫內容！"
        if login_form.is_valid():
            user_email = login_form.cleaned_data['user_email']

            password = login_form.cleaned_data['password']
            try:
                user = models.Member.objects.get(e_mail=user_email)

                if not user.has_confirmed:
                    message = "該用戶還未通過信箱認證！"
                    return render(request, 'client/login.html', locals())
                if user.member_password == hash_code(password):  # 哈希值和数据库内的值进行比对
                    request.session['is_login'] = True
                    request.session['user_id'] = user.phone_number
                    request.session['user_email'] = user.e_mail
                    request.session['user_name'] = user.member_name
                    request.session['user_img'] = user.photo.url
                    return redirect('/index/')
                else:
                    message = "密碼不正確！"
            except:
                message = "此用戶不存在！"

        return render(request, 'client/login.html', locals())

    login_form = forms.UserForm()
    return render(request, 'client/login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        # 登录状态不允许注册。
        return redirect("/index/")
    if request.method == "POST":
        register_form = forms.RegisterForm(request.POST, request.FILES)
        message = "請檢查填寫內容！"
        if register_form.is_valid():  # 获取数据
            email = register_form.cleaned_data['email']
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            sex = register_form.cleaned_data['sex']
            phone_number = register_form.cleaned_data['phone_number']
            image = register_form.cleaned_data['image']
            birthday = register_form.cleaned_data['birthday']
            if password1 != password2:  # 判断两次密码是否相同
                message = "兩次輸入的密碼不同！"
                return render(request, 'client/register.html', locals())
            else:
                same_email_user = models.Member.objects.filter(e_mail=email)
                if same_email_user:  # 信箱唯一
                    message = '該信箱已被使用，請選擇其他信箱！'
                    return render(request, 'client/register.html', locals())
                same_phone_number_user = models.Member.objects.filter(phone_number=phone_number)
                if same_phone_number_user:  # 電話唯一
                    message = '該電話已經被使用，請選擇其他電話！'
                    return render(request, 'client/register.html', locals())
                if birthday > datetime.date.today():  # 電話唯一
                    message = '生日不能超過今天日期！'
                    return render(request, 'client/register.html', locals())

                # 当一切都OK的情况下，创建新用户

                new_user = models.Member()
                new_user.member_name = username
                new_user.member_password = hash_code(password1)  # 使用加密密码
                new_user.e_mail = email
                new_user.gender = sex
                new_user.photo = image
                new_user.phone_number = phone_number
                new_user.birthdate = birthday
                new_user.save()
                code = make_confirm_string(new_user)

                send_email(email, code)
                message = '請前往註冊信箱，進行認證！'
                return render(request, 'client/confirm.html', locals())  # 跳转到等待邮件确认页面。
    register_form = forms.RegisterForm()
    return render(request, 'client/register.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/index/")
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/index/")  # logout後，redirect會將頁面重新導向index


def hash_code(s, salt='mysite4'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


def make_confirm_string(user):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    code = hash_code(user.member_name, now)
    models.ConfirmString.objects.create(code=code, c_user=user, )
    return code


def send_email(email, code):
    from django.core.mail import EmailMultiAlternatives

    subject = '来自吃冰102的註冊信件'

    text_content = '''感谢註冊www.cb102.com，這裡充滿各種高大上的物品！\
                    如果你看到这條消息，說明您的信箱服務器不提供HTML連接，請盡速聯繫管理員！'''

    html_content = '''
                    <p>感謝註冊<a href="https://{}/confirm/?code={}" target=blank>www.cb102.com</a>，\
                    這裡是吃冰102的線上網站，註冊后可享受高科技購物！</p>
                    <p>請點擊鏈接完成註冊！</p>
                    <p>此鏈接有效期為{}天！</p>
                    '''.format(settings.ALLOWED_HOSTS[0] + ':8000', code, settings.CONFIRM_DAYS)

    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


def user_confirm(request):
    code = request.GET.get('code', None)
    message = ''
    try:
        confirm = models.ConfirmString.objects.get(code=code)
    except:
        message = '無效的確認請求!'
        return render(request, 'client/confirm.html', locals())

    c_time = confirm.c_time
    now = datetime.datetime.now()
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的信箱已過期！請重新註冊!'
        return render(request, 'client/confirm.html', locals())
    else:
        confirm.c_user.has_confirmed = True
        confirm.c_user.save()
        confirm.delete()
        message = '感謝您的認證，請使用帳號登入！'
        return render(request, 'client/confirm.html', locals())


def get_record(request):
    if not request.session.get('is_login', None):
        return redirect("/index/")
    records = models.InOrOut.objects.filter(phone_number=request.session.get('user_id')).order_by('-order_date') \
        .prefetch_related('orderdetail_set')

    return render(request, 'client/record.html', locals())


def get_profile(request):
    if not request.session.get('is_login', None):
        return redirect("/index/")
    user_profile = models.Member.objects.filter(phone_number=request.session.get('user_id'))
    records = models.InOrOut.objects.filter(phone_number=request.session.get('user_id')).order_by('-come_time') \
        .prefetch_related('purchase_set')
    return render(request, 'client/profile.html', locals())


def take_pic(request):
    # import os
    # try:
    #     path = "/Users/jiangbifeng/work/django2/unmanned/dataset/{}".format(request.session.get('user_id'))
    #     os.mkdir(path)
    # except:
    #     pass
    # os.system('/Users/jiangbifeng/.pyenv/versions/3.6.5/bin/python '
    #           '/Users/jiangbifeng/work/django2/unmanned/take_face_pictures.py '
    #           '--cascade haarcascade_frontalface_default.xml --output {}'.format(path))
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/index/")
    return render(request, 'client/take_pic.html')


@csrf_exempt
def upload_image(request):
    path = os.path.join(settings.BASE_DIR, "dataset")
    try:
        path = str(path) + "/" + request.session.get('user_id')
        os.mkdir(path)
    except:
        pass
    try:
        data = json.loads(request.POST['data'])
        data = list(map(lambda x: re.sub('data:image/png;base64,', '', x), data))
        data = list(map(lambda x: base64.b64decode(x), data))
        for i, img_data in enumerate(data):
            with open("%s/%s.jpg" % (path, i), "wb") as img_file:
                img_file.write(img_data)
        has_pic = models.Member.objects.get(phone_number=request.session.get('user_id'))
        has_pic.has_photo = True
        has_pic.save()
    except:
        pass

    return HttpResponse("uploaded")


def test_page(request):
    pass
    return render(request, "client/test.html")


# ____（分割線）以下為admin端____


def admin_report(request):
    category = models.Category.objects.all()
    member = models.Member.objects.all()
    purchase = models.Product.objects.raw("""select case  count(quantity)
                                                          when 0 then 0
                                                          else sum(quantity) 
                                                          end qty,
                                                    product_name,
                                                    case  count(quantity)
                                                          when 0 then 0
                                                          else sum(quantity*price)
                                                          end total,
                                                    product_name,
                                                    product.product_id ,count(quantity) as times
                                             from product

unmanned/templates/client/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>
    <!-- icon -->
    <link rel="Shortcut Icon" type="image/x-icon" href="{% static 'icon/icon.png' %}"/>
    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block scripts %}{% endblock %}
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav"
                    aria-expanded="false">
                <span class="sr-only">切換導航條</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Unmanned-Store</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
            <!--<ul class="nav navbar-nav">
              <li class="active"><a href="/index/">首頁</a></li>
            </ul>-->
            <ul class="nav navbar-nav navbar-right">
                {% if request.session.is_login %}
                    <li><a href="/profile/"><img class="" src="{{ request.session.user_img }}" height="25" width="28"
                                                 style="border-radius: 50%">個人資料</a></li>
                    <li><a href="/logout/">登出</a></li>
                {% else %}
                    <li><a href="/login">登入</a></li>
                    <li><a href="/register/">註冊</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('img.captcha').click(function () {
            var $form = $(this).parents('form');
            var url = location.protocol + "//" + window.location.hostname + ":" + location.port + "/captcha/refresh/";
            $.getJSON(url, {}, function (json) {
                $form.find('input[name="captcha_0"]').val(json.key);
                $form.find('img.captcha').attr('src', json.image_url);
            });
            return false;
        });
    });
</script>
</body>
</html>

unmanned/templates/client/confirm.html
{% extends 'client/base.html' %}
{% block title %}註冊確認{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-center">{{ message }}</h1>
    </div>
    <script>
        window.setTimeout("window.location='/login/'",2000);
    </script>
{% endblock %}

unmanned/templates/client/profile.html
{% extends 'client/base.html' %}
{% load staticfiles %}
{% load client_extras %}
{% block title %}個人資料{% endblock %}
{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet"/>
{% endblock %}
{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("a").click(function () {
                $('#' + $(this).attr('target')).toggleClass('hidden');
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <ul id="myTab" class="nav nav-tabs">
            <li class="active">
                <a href="#personal" data-toggle="tab">
                    個人資料
                </a>
            </li>
            <li><a href="#record" data-toggle="tab">購買記錄</a></li>

        </ul>

        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="personal">
                {% if request.session.is_login %}
                    <div class="row">
                        <div class="col-md-6 ">
                            <div class="panel panel-default">
                                <div class="panel-body">

                                    <div class="box box-info">

                                        <div class="box-body">
                                            <div class="col-sm-6">
                                                <div align="center">
                                                    <img alt="User Pic"
                                                         src="{{ request.session.user_img }}"
                                                         id="profile-image1" class="img-circle img-responsive">
                                                </div>
                                                <br>

                                            </div>
                                            {% for user_profile in user_profile %}
                                                {% if not user_profile.has_photo %}
                                                    <div class="col-sm-6">
                                                        <form method="get" action="take_pic/">
                                                            想入店？讓我們來
                                                            <button type="submit">拍照</button>
                                                            吧~(✿◡‿◡)
                                                        </form>
                                                    </div>
                                                {% elif user_profile.line_account is None %}
                                                    <div class="col-sm-6">
                                                        <h4>最後將我們加為Line好友吧~</h4>
                                                        <img src="{% static 'icon/line_QRcode.png' %}" height="100" width="100">
                                                    </div>
                                                {% else %}    
                                                    <div class="col-sm-6">
                                                        <form method="get" action="take_pic/">
                                                            您已被識別，還想再
                                                            <button type="submit">拍一次</button>
                                                            嗎(*^▽^*)？
                                                        </form>
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                            <div class="clearfix"></div>
                                            <hr style="margin:5px 0 5px 0;">

                                            {% for user_profile in user_profile %}
                                                <div class="col-sm-5 col-xs-6 tital ">姓名：</div>
                                                <div class="col-sm-7"> {{ user_profile.member_name }}</div>

                                                <div class="clearfix"></div>
                                                <div class="bot-border"></div>

                                                <div class="col-sm-5 col-xs-6 tital ">性別：</div>
                                                <div class="col-sm-7">{{ user_profile.get_gender_display }}</div>

                                                <div class="clearfix"></div>
                                                <div class="bot-border"></div>

                                                <div class="col-sm-5 col-xs-6 tital ">電話：</div>
                                                <div class="col-sm-7">{{ user_profile.phone_number }}</div>

                                                <div class="clearfix"></div>
                                                <div class="bot-border"></div>

                                                <div class="col-sm-5 col-xs-6 tital ">生日：</div>
                                                <div class="col-sm-7">{{ user_profile.birthdate|date:'Y-m-d' }}</div>

                                                <div class="clearfix"></div>
                                                <div class="bot-border"></div>

                                                <div class="col-sm-5 col-xs-6 tital ">E-Mail：</div>
                                                <div class="col-sm-7">{{ user_profile.e_mail }}</div>

                                                <div class="clearfix"></div>
                                                <div class="bot-border"></div>

                                            {% endfor %}
                                            <!-- /.box-body -->
                                        </div>
                                        <!-- /.box -->

                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>

            <div class="tab-pane fade" id="record" style="overflow-x:auto;">
                {% if request.session.is_login %}

                    <table class="table_outside" border="1" width="60%">
                        <tr>
                            <td>
                                <table border="1" width="100%">
                                    <tr style="background-color: #556688; color: #bce8f1">
                                        <td width="25%">訂單編號</td>
                                        <td width="25%">日期</td>
                                        <td width="25%">消費金額</td>
                                        <td width="25%">詳細資料</td>
                                    </tr>
                                </table>

                                <table border="1" width="100%">
                                    {% for record in records %}
                                        {% if record.purchase_set.count == 0 %}
                                        {% else %}
					<tr>
                                            <td width="25%">{{ record.come_time|time_tran }}</td>
					    <td width="25%">{{ record.come_time|date:'Y-m-d' }}</td>
					    <td width="25%">{{ record.come_time|date:'Y-m-d H:i'|all_price }}</td>
				   	    <td width="25%"><a target={{ record.come_time|time_tran }}>查看/隱藏</a></td>
					</tr>
                                        <tr>
                                            <td colspan="4" style="padding:10px;">
                                                <table class="hidden table_inside"
                                                       id={{ record.come_time|time_tran }}  border="0" width="100%">

                                                    <tr style="color: #01814a">
                                                        <td width="25%">品項名稱</td>
                                                        <td width="25%">單價</td>
                                                        <td width="25%">數量</td>
                                                        <td width="25%">總價</td>
                                                    </tr>

                                                    {% for product in record.purchase_set.all %}
                                                        <tr>
                                                            <td width="20%">{{ product.product }}</td>
                                                            <td width="20%">{{ product.product.price }}</td>
                                                            <td width="20%">{{ product.quantity }}</td>
                                                            <td width="20%">{% widthratio product.quantity 1 product.product.price %}</td>

                                                        </tr>
                                                    {% endfor %}
                                                </table>
                                            </td>
                                        </tr>
					{% endif %}
                                    {% empty %}
                                        {% for user_profile in user_profile %}
                                            {% if not user_profile.has_photo %}
                                                <div class="col-sm-6">
                                                    <form method="get" action="take_pic/">
                                                        想入店？讓我們來
                                                        <button type="submit">拍照</button>
                                                        吧~(✿◡‿◡)
                                                    </form>
                                                </div>
                                            {% else %}
                                                <div class="col-sm-6">
                                                    <form>
                                                        您還沒有消費記錄喲~
                                                    </form>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    {% endfor %}
                                </table>
                            </td>
                        </tr>


                    </table>
                {% endif %}
            </div>
        </div>
        {#        <form method="get" action="record/">#}
        {#            <button type="submit">購買記錄</button>#}
        {#        </form>#}

    </div>
{% endblock %}